export enum ACCESS_NAME {
  ACTION_LOG_LIST = "ActionLogListView",
  APPLICATION = "ApplicationViewSet",
  SSO_USER = "SsoUserViewSet",
  COMPANY_BY_TIN = "CompanyByTinView",
  COMPANY_MEMBER = "CompanyMemberCRUDAPIView",
  COMPANY_CATEGORY = "CompanyCategoryCRUDAPIView",
  CHAIN = "ChainCRUDAPIView",
  COMPANY = "CompanyCRUDAPIView",
  COMPANY_MEDIA = "CompanyMediaCRUDAPIView",
  PRODUCT = "ProductCRUDAPIView",
  COMPANY_ACCESS_APPLICATION = "CompanyAccessApplicationViewSet",
  COMPANY_VERIFICATION = "CompanyVerificationViewSet",
  USER_ACHIEVEMENT_LIST = "UserAchievementListAPIView",
  USER_REACTION_LIST = "UserReactionListAPIView",
  AWARDED_USERS = "AwardedUsersAPIView",
  REVIEW = "ReviewViewSet",
  MAIN_PAGE_CATEGORY = "MainPageCategoryViewSet",
  REVIEW_USER = "ReviewUserViewSet",
  REVIEW_MEDIA = "ReviewMediaViewSet",
  REVIEW_REPLY = "ReviewReplyViewSet",
  ACHIEVEMENT = "AchievementViewSet",
  USER_ACHIEVEMENT = "UserAchievementViewSet",
  USER_WITHDRAWS = "UserWithdrawsViewSet",
  COMPLAINT = "ComplaintViewSet",
  CARE_TRANSACTION_LIST = "CareTransactionListAPIView",
  ADMIN = "AdminViewSet",
  STATISTIC = "StatisticViewSet",
  NOTIFICATION_SETTINGS = "NotificationSettingViewSet",
  TRANSLATION = "TranslationViewSet",
  MODERATION_STATISTICS = "ModerationStatisticsView",
  BLOG = "BlogViewSet",
  BLOG_TAG = "BlogTagViewSet",
  MODERATOR = "ModeratorCRUDAPIView",
}

export enum ACCESS_ACTION {
  ALL = "*",
  LIST = "list", // You can get a list of items
  RETRIEVE = "retrieve", // You can get a single item of list
  GET = "get", // You can get a object of non-list item
  CREATE = "create",
  UPDATE = "update",
  PARTIAL_UPDATE = "partial_update",
  DESTROY = "destroy",
  BLOCK = "block",
  UNBLOCK = "unblock",
  MODERATE = "moderate",
  MODERATE_MANY = "moderate_many",
  MODERATE_PENDING = "moderation_pending",
  CONFIRM = "confirm",
  REJECT = "reject",
  REVIEW = "review",
  REVIEW_GRAPH = "review_graph",
}
